package com.svtt.carrierconfig.data.repository

import com.svtt.carrierconfig.data.model.CarrierConfigKey
import com.svtt.carrierconfig.data.model.ConfigValueType
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import timber.log.Timber
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class OverrideXmlBuilder @Inject constructor() {
    
    /**
     * Build CarrierConfig override XML from list of keys
     */
    suspend fun buildXml(keys: List<CarrierConfigKey>): String = withContext(Dispatchers.IO) {
        try {
            val xml = buildString {
                appendLine("<?xml version=\"1.0\" encoding=\"utf-8\"?>")
                appendLine("<!-- Generated by SVTT CarrierConfig Override -->")
                appendLine("<carrier_config_list>")
                appendLine("    <carrier_config>")
                
                for (key in keys) {
                    appendLine("        ${formatKeyAsXml(key)}")
                }
                
                appendLine("    </carrier_config>")
                appendLine("</carrier_config_list>")
            }
            
            Timber.d("Generated XML with ${keys.size} keys")
            xml
        } catch (e: Exception) {
            Timber.e(e, "Failed to build XML")
            throw e
        }
    }
    
    /**
     * Format a single key as XML element
     */
    private fun formatKeyAsXml(key: CarrierConfigKey): String {
        return when (key.type) {
            ConfigValueType.BOOLEAN -> {
                val value = if (key.value as Boolean) "true" else "false"
                """<boolean name="${key.key}" value="$value" />"""
            }
            ConfigValueType.INTEGER -> {
                """<int name="${key.key}" value="${key.value}" />"""
            }
            ConfigValueType.STRING -> {
                """<string name="${key.key}">${escapeXml(key.value.toString())}</string>"""
            }
            ConfigValueType.STRING_ARRAY -> {
                buildString {
                    append("""<string-array name="${key.key}" num="0">""")
                    // TODO: Handle array values if needed
                    append("</string-array>")
                }
            }
        }
    }
    
    /**
     * Escape XML special characters
     */
    private fun escapeXml(input: String): String {
        return input
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\"", "&quot;")
            .replace("'", "&apos;")
    }
    
    /**
     * Validate XML syntax
     */
    suspend fun validateXml(xml: String): Boolean = withContext(Dispatchers.IO) {
        try {
            // Basic validation checks
            if (!xml.contains("<?xml")) return@withContext false
            if (!xml.contains("<carrier_config_list>")) return@withContext false
            if (!xml.contains("</carrier_config_list>")) return@withContext false
            
            // Count opening and closing tags
            val openCount = xml.count { it == '<' }
            val closeCount = xml.count { it == '>' }
            if (openCount != closeCount) return@withContext false
            
            Timber.d("XML validation passed")
            true
        } catch (e: Exception) {
            Timber.e(e, "XML validation failed")
            false
        }
    }
}
